witnet/my-wit-wallet

lib/util/preferences.dart

return `null` instead of `""` to be able to catch the null value with `??` operator

fix: allow to import first wallet from xprv

---

.github/workflows/main.yml
lib/util/storage/database/account_repository.dart
lib/util/storage/database/encrypt/keychain.dart
lib/util/storage/database/transaction_repository.dart
lib/util/storage/database/wallet_repository.dart

- update `.github/workflows/main.yml`
- roll channel to `beta`
- force strong types for database objects build was failing because of returning `Object?`

fix: github ci build

---

lib/widgets/address_list.dart
lib/widgets/input_amount.dart
lib/widgets/layouts/dashboard_layout.dart
lib/widgets/transaction_details.dart
lib/widgets/transactions_list.dart
lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/01_recipient_step.dart
lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/02_review_step.dart

- Implement `amount_input` widget and add unit suffix
- Substitutes Wit string and uses Wit enum name
close #87

feat(amount_input): implement amount input with unit suffix

---

macos/Runner/Release.entitlements

For the Release version we needed to enable `com.apple.security.network.client`
it is already present in the debug entitlements

fix: macos preventing internet connection on release version

---

lib/widgets/layouts/dashboard_layout.dart

a fix is to get the currentRoute and and check if it matches what which route the button represents. if it is a match -> pass an empty function, if it is not -> trigger the navigation

fix: Avoid navigation in to the current route

---

lib/bloc/explorer/explorer_bloc.dart

For unconfirmed transactions, the `getVtt` method returns a `ValueTransferInfo`  for mined / confirmed txns or a `HashInfo` if the transaction is still pending. wrapping it in a try catch block removes the error.

Fix: Error on Pending TX

---

lib/widgets/wallet_list.dart

Adds SafeArea to avoid hide content by the bottom-bar of the device.
close #106

fix(wallet_list): add SafeArea to wallet list

---

lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/02_select_miner_fee.dart

When changing a custom fee, the unit conversion from `Wit` to `nanoWit` was reversed.

fix(02_select_miner_fee): fix conversion when custom fee input changes

---

lib/util/storage/database/wallet.dart

The list of addresses that is used to sync only included the external accounts. uncomment the line to add the internal accounts to the address list to sync.
Closes #127

Fix (wallet): balance sync

---

lib/widgets/link.dart

This fixes the problem with `url_launcher` library and Android11.
close #146

fix(link): allow open external links in android

---

ios/Runner.xcodeproj/project.pbxproj
ios/Runner/Runner.entitlements
ios/Runner/RunnerDebug.entitlements
ios/Runner/RunnerRelease.entitlements

The warning 'Missing Push Notification Entitlement', after building to Apple TestFlight should be ignored as we don't use push notifications.
Flutter open issues to follow: [#14182](https://github.com/flutter/flutter/issues/14182),  [#9984](https://github.com/flutter/flutter/issues/9984).

fix: delete aps-environment ios entitlements

---

android/app/src/main/AndroidManifest.xml

Delete the meta-data element, as Flutter no longer uses that, but it can cause a crash.
https://docs.flutter.dev/release/breaking-changes/splash-screen-migration

fix: Android Deprecated Splash Screen API Migration

---

lib/constants.dart
lib/screens/create_wallet/enc_xprv_card.dart
lib/widgets/layouts/dashboard_layout.dart
lib/widgets/layouts/layout.dart
lib/widgets/select.dart
lib/widgets/select_wallet_box.dart
lib/widgets/wallet_type_label.dart

- [Remove wallet type label for hd wallets](https://github.com/witnet/my-wit-wallet/pull/310/commits/536d3cb11276bf8190418adf2508e1223b3f8fee)
- [Add select for selecting xprv origin](https://github.com/witnet/my-wit-wallet/pull/310/commits/9dc5012dc875177c2bd9dbafd5e7cad356414c19)
close #309

Update UX for single address wallets

---

lib/constants.dart

Increasing the external gap limit to 10 will match the gap limit in witnet-rust / Sheikah.
Closes #279

Fix: Increase External Gap Limit

---

lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/02_select_miner_fee.dart

This warning appeared every time the user go to the next step having the keyboard open in i0S:
```
[LayoutConstraints] Unable to simultaneously satisfy constraints.
Probably at least one of the constraints in the following list is one you don't want.
Try this:
(1) look at each constraint and try to figure out which you don't expect;
(2) find the code that added the unwanted constraint or constraints and fix it.
(
"<NSLayoutConstraint:0x281e81db0 'assistantHeight' SystemInputAssistantView.height == 44   (active, names: SystemInputAssistantView:0x12962dc20 )>",
"<NSLayoutConstraint:0x281eccdc0 'assistantView.bottom' SystemInputAssistantView.bottom == _UIKBCompatInputView:0x127e1c7d0.top   (active, names: SystemInputAssistantView:0x12962dc20 )>",
"<NSLayoutConstraint:0x281ecfa20 …
```

fix: avoid warning when going from miner fee step to review step

---

lib/bloc/crypto/api_crypto.dart
lib/bloc/crypto/crypto_bloc.dart
lib/bloc/crypto/crypto_isolate.dart

- add method in crypto_isolate.dart to sign a message
- add wrapper in api_crypto.dart to call the isolate method
to call the method from anywhere in myWitWallet after the wallet is unlocked:
`Map<String, dynamic> signedMessage = await Locator.instance.get<ApiCrypto>().signMessage("Hello World", "wit1...");`

feat: add signMessage method

---

android/app/build.gradle

Flutter does not support `x86` architecture. Check [supported architectures for android.](https://docs.flutter.dev/deployment/android#what-are-the-supported-target-architectures)
Check [issue](https://github.com/flutter/flutter/issues/37396#issuecomment-1207203921) in flutter.

chore: delete `x86` from android build config

---

.github/workflows/main.yml

By default, the setup task picks up the latest version of the tool, and it just got updated with dotnet 8. You have to add the setup dotnet task before this task:
```yaml
- uses: actions/setup-dotnet@v3
with:
dotnet-version: '8.0.x'
```
The agents haven't been updated yet, so you need this until they have it installed by default.
_Originally posted by @azchohfi in https://github.com/microsoft/setup-msstore-cli/issues/133#issuecomment-1815881944_

ci(windows): set dotnet-version v8

---

lib/bloc/crypto/crypto_bloc.dart
lib/bloc/crypto/crypto_state.dart
lib/bloc/explorer/api_explorer.dart
lib/bloc/explorer/explorer_bloc.dart
lib/screens/create_wallet/build_wallet_card.dart
lib/util/storage/database/account.dart
lib/util/storage/database/balance_info.dart
lib/util/storage/database/database_service.dart
lib/util/storage/database/wallet.dart

- emit `CryptoInitializingWalletState` for every transaction during the initial sync.
- only display `localization.exploredAddresses` for hd wallets
Closes #451

feat: add transaction sync to BlocEvent

---

lib/l10n/app_en.arb
lib/l10n/app_es.arb
lib/screens/login/view/init_screen.dart
lib/screens/receive_transaction/address_list_view.dart
lib/screens/receive_transaction/receive_tx_screen.dart
lib/util/storage/database/wallet.dart
lib/widgets/PaddedButton.dart
lib/widgets/address_item.dart
lib/widgets/address_list.dart
lib/widgets/speed_up_tx.dart
lib/widgets/witnet/transactions/value_transfer/modals/new_address_modal.dart

close https://github.com/witnet/my-wit-wallet/issues/523

Redesign receive screen
