- lib/util/preferences.dart
- lib/widgets/wallet_list.dart
This pr fixes the `wallet_list` widget. Now, each wallet card shows the correct selected address.
> Fix wallet list selected account

- lib/widgets/identicon.dart
- lib/widgets/layouts/layout.dart
- lib/widgets/wallet_list.dart
- pubspec.yaml
add lib/widgets/identicon.dart
roll dart version in pubspec.yaml to 2.14.0 to use the triple shift operator `>>>` add IdenticonWidget for the wallet id image.
> Feat: Add Identicon Widget

- android/app/build.gradle
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- set `multiDexEnabled` to true
- update Gradle version and distributionUrl
> chore: update android build

- android/app/src/main/AndroidManifest.xml
- macos/Runner/DebugProfile.entitlements
- macos/Runner/Release.entitlements
> Give internet access

- ios/Runner.xcodeproj/project.pbxproj
- lib/screens/login/view/login_screen.dart
- lib/util/storage/database/account_repository.dart
- lib/util/storage/database/encrypt/keychain.dart
- lib/util/storage/database/wallet_repository.dart
- Fixes the login error
- Fixes the globalkey error when login
> Fix login and globalkey error

- lib/util/extensions/text_input_formatter.dart
- lib/util/storage/database/balance_info.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/01_recipient_step.dart
- changed all TextFields to TextFormFields - reworked the validators to return String? instead of void. if it is valid it returns null, if it is not valid it returns an error message. - moved the state changes to the onChanged controllers in form
- added `WitValueFormatter` Max number of decimals is 9 Max whole-number is 10
- added `WitAddressFormatter` max length is 42
> fix: vtt validations

- lib/bloc/crypto/api_crypto.dart
- lib/bloc/crypto/crypto_bloc.dart
- lib/bloc/crypto/crypto_isolate.dart
- provide some of the more CPU intensive methods via the isolate. an isolate is a separate thread. when calling these methods from the main thread it can block the animation / UI.
> feat: Additional Isolate Methods

- lib/util/storage/database/encrypt/keychain.dart
- lib/util/storage/database/transaction_repository.dart
The Build in GitHub Actions was failing.
fixed the errors it was complaining about.
we did not change anything in the related files in the past commits so i have no idea why the build was breaking on github but not locally without these changes
> fix: github actions build

- lib/screens/create_wallet/bloc/create_wallet_bloc.dart
- lib/screens/create_wallet/create_wallet_screen.dart
- lib/screens/create_wallet/enc_xprv_card.dart
- lib/screens/create_wallet/encrypt_wallet_card.dart
- lib/screens/create_wallet/select_imported_option.dart
- lib/screens/dashboard/bloc/dashboard_bloc.dart
- lib/util/preferences.dart
- lib/util/storage/database/encrypt/keychain.dart
- lib/util/storage/database/transaction_repository.dart
- Force clear next actions when clicking next in `select_imported_option`
- Conditionally render correct view when going back from `wallet_detail_card`
close #100
> fix: render correct screen when going back from `wallet_detail_card`

- lib/widgets/transactions_list.dart
> fix: replace "Several addresses" with the first address

- lib/screens/preferences/general_config.dart
- lib/theme/dark_theme.dart
- lib/widgets/PaddedButton.dart
- lib/widgets/input_amount.dart
- lib/widgets/transaction_details.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/01_recipient_step.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/02_review_step.dart
- Uses primary style for Lock wallet button
close #54
> feat(general_config): update lock btn and use secondary style

- lib/screens/send_transaction/send_vtt_screen.dart
- lib/widgets/layouts/dashboard_layout.dart
- lib/widgets/layouts/layout.dart
> Scroll to top when navigating between routes and cards

- lib/widgets/layouts/dashboard_layout.dart
Updates send and receive icons from `paperPlane` to `locationArrow`
close #114
> feat(dashboard_layout): update send and receive icon

- lib/screens/create_wallet/create_import_wallet.dart
- lib/widgets/wallet_list.dart
> fix(navigation): avoid overlapping route states

- lib/widgets/wallet_list.dart
> fix(wallet_list): update unit from nanoWit to Wit

- lib/screens/create_wallet/enc_xprv_card.dart
- lib/screens/create_wallet/encrypt_wallet_card.dart
- lib/screens/create_wallet/wallet_detail_card.dart
- lib/widgets/verify_password.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/01_recipient_step.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/02_select_miner_fee.dart
Updates last input in all forms to hide keyboard on clicking enter.
close #144
> feat: hide keyboard on click enter

- lib/main.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
> feat: set minimumSize for desktop and custom window

- lib/bloc/transactions/value_transfer/vtt_create/vtt_create_bloc.dart
- reload the database after it has synced and refresh the walletStorage instance sharedPreferences
> fix: wallet sync issue

- lib/screens/create_wallet/disclaimer_card.dart
No need to merge this PR yet, I may push some more fixes for typos if I encounter them. Feel free to comment and voice any disagreements with a specific commit.
fix #136
> Fix several typos

- lib/bloc/explorer/explorer_bloc.dart
- lib/util/storage/database/wallet.dart
ensure that newly created accounts are added to the database, and then reload the database.
> Fix(sync): Ensure Gap Limit

- lib/widgets/wallet_list.dart
~AFAIK, this proposal was made by @aesedepece months ago~
_Originally posted by @aesedepece in https://github.com/witnet/internal/issues/256#issuecomment-1265165785_
> chore: update wallet_list text to create wallet button

- android/app/build.gradle
- android/app/src/debug/AndroidManifest.xml
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/kotlin/io/witnet/witnet_wallet/MainActivity.kt
- android/app/src/profile/AndroidManifest.xml
- ios/Runner.xcodeproj/project.pbxproj
- linux/CMakeLists.txt
- macos/Runner/Configs/AppInfo.xcconfig
- windows/runner/Runner.rc
> Fix: change app Package from `com` to `io`

- lib/widgets/layouts/layout.dart
- lib/widgets/transaction_details.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/03_review_step.dart
- Avoid showing timestamp when pending tx close #196 
- Update theme for android native bar close #160
> Small fixes

- lib/screens/receive_transaction/receive_tx_screen.dart
> feat(receive_tx_screen): improve ux of copy address

- lib/screens/create_wallet/confirm_mnemonic_card.dart
- lib/screens/create_wallet/create_wallet_screen.dart
- lib/screens/create_wallet/enc_xprv_card.dart
- lib/screens/create_wallet/encrypt_wallet_card.dart
- lib/screens/create_wallet/import_mnemonic_card.dart
- lib/screens/create_wallet/wallet_detail_card.dart
- lib/screens/create_wallet/xprv_card.dart
- lib/screens/dashboard/view/dashboard_screen.dart
- lib/screens/login/view/login_screen.dart
- lib/screens/preferences/preferences_screen.dart
- lib/screens/preferences/wallet_config.dart
- lib/screens/send_transaction/send_vtt_screen.dart
- lib/widgets/generate_compatible_xprv.dart
- lib/widgets/verify_password.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/01_recipient_step.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/02_select_miner_fee.dart
> feat(ux): trigger submission on enter

- lib/util/extensions/num_extensions.dart
- test/extensions/standardize_wit_units_test.dart
> fix(standardize_wit_units): avoid using toStringAsFixed to truncate

- lib/constants.dart
> fix: increase gap limit

- lib/constants.dart
- lib/screens/create_wallet/build_wallet_card.dart
- lib/screens/create_wallet/wallet_detail_card.dart
- lib/screens/preferences/wallet_config.dart
- lib/widgets/address_list.dart
- lib/widgets/input_amount.dart
- lib/widgets/layouts/dashboard_layout.dart
- lib/widgets/transaction_details.dart
- lib/widgets/transactions_list.dart
- lib/widgets/wallet_list.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/01_recipient_step.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/02_select_miner_fee.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/03_review_step.dart
close #222 
close #220 
close #218 
close #197
> Fix copies

- lib/screens/receive_transaction/receive_tx_screen.dart
- lib/theme/colors.dart
- lib/theme/extended_theme.dart
- lib/widgets/layouts/dashboard_layout.dart
- lib/widgets/layouts/layout.dart
- lib/widgets/snack_bars.dart
> feat(snackbars): add new style and show connection snackbar in layout

- lib/bloc/crypto/crypto_bloc.dart
- lib/util/preferences.dart
> fix: set preferences after re-import wallet

- lib/constants.dart
- lib/screens/preferences/general_config.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile.lock
- pubspec.yaml
> fix(general_config): get version from constant

- android/gradle.properties
> feat: allow depreciated NDK for older Android devices

- lib/constants.dart
```
Version: 0.1.1-dev
Release type: patch
Criticality: non-critical
```
Relevant commits:
- [fix(dashboard_screen): avoid showing paginator in transaction details](https://github.com/witnet/my-wit-wallet/commit/6ff482ecaaaac3cb7de05e5d92a6e43f4b748371)
- [feat: handle connection error when initializing wallet ftu](https://github.com/witnet/my-wit-wallet/commit/05a0e48078bd9d854a74c79d3ecfae5d5e44ddb2)
- [fix(general_config): get version from constant](https://github.com/witnet/my-wit-wallet/commit/f7632cec8d7db15e66af4c4754f4e3815ea5e321)
- [fix(accesibility): add semantics to non-labeled widgets](https://github.com/witnet/my-wit-wallet/commit/01ad30997619207d999ac69855558c056ba53a4c)
- [fix(accesibility): add new btn types and update focus …
> chore: bump v0.1.1-dev

- lib/screens/preferences/general_config.dart
- lib/widgets/layouts/dashboard_layout.dart
- lib/widgets/layouts/layout.dart
- lib/widgets/layouts/listen_fourth_button.dart
- lib/widgets/wallet_list.dart
> feat(accesibility): add shortcut for going back in dashboard view

- lib/bloc/crypto/api_crypto.dart
- lib/bloc/crypto/crypto_bloc.dart
- lib/bloc/crypto/crypto_event.dart
- lib/bloc/crypto/crypto_isolate.dart
- lib/constants.dart
- lib/screens/create_wallet/bloc/api_create_wallet.dart
- lib/screens/create_wallet/bloc/create_wallet_bloc.dart
- lib/screens/create_wallet/build_wallet_card.dart
- lib/screens/create_wallet/wallet_detail_card.dart
- lib/util/storage/database/wallet.dart
- lib/util/storage/database/wallet_repository.dart
- lib/util/storage/database/wallet_storage.dart
- lib/util/witnet/wallet/wallet.dart
> feat: delete wallet description feature

- lib/widgets/address_list.dart
- lib/widgets/layouts/dashboard_layout.dart
- lib/widgets/transactions_list.dart
> feat: add semantics to transactions and addresses

- lib/widgets/layouts/dashboard_layout.dart
> fix: avoid default transitions when new route is pushed

- lib/screens/create_wallet/enc_xprv_card.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/qr_scanner.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/01_recipient_step.dart
- Fix save import type index
- Fix back navigation in qr scanner
> Fix import xprv bugs

- lib/util/extensions/num_extensions.dart
- test/extensions/standardize_wit_units_test.dart
> fix: format number

- .env.example
- integration_test/import_mnemonic_test.dart
- lib/util/integration_test_utils.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
`$ flutter test integration_test/import_mnemonic_test.dart `
This will build the wallet and automatically test importing a mnemonic.
- if there is no wallet database it will set the password
- if there is a wallet database, it will check the `.env` file for the password.
> Feat(Integration Test): add Import Mnemonic test

- windows/runner/CMakeLists.txt
- windows/runner/main.cpp
- windows/runner/window_configuration.cpp
- windows/runner/window_configuration.h
- add `windows/runner/window_configuration.cpp` and `.h`
- move the default window settings to the configuration file.
- add the `window_configuration.cpp` file to the CMAKE list.
#317
> Fix(Windows): Window Size and Position on launch

- linux/CMakeLists.txt
- linux/my_application.cc
- linux/window_configuration.cc
- linux/window_configuration.h
- add `linux/window_configuration.cc` and `.h`
- move the default window settings to the configuration file.
- add the `window_configuration.cc` file to the CMAKE list.
#317
> Fix(Linux): Window Size and Position on launch

- lib/screens/preferences/general_config.dart
- lib/widgets/layouts/dashboard_layout.dart
> fix: avoid rendering twice the login screen

- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- lib/theme/dark_theme.dart
- lib/theme/light_theme.dart
> fix(style): fix checkbox fill color due to flutter update

- lib/bloc/crypto/crypto_bloc.dart
- lib/screens/create_wallet/build_wallet_card.dart
- lib/screens/create_wallet/enc_xprv_card.dart
- macos/Podfile.lock
- macos/Runner.xcodeproj/project.pbxproj
- macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
> fix: avoid IOS shader error deleting linear gradients

- macos/Runner/Base.lproj/MainMenu.xib
> fix: update macos window size on launch

- lib/constants.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/03_review_step.dart
- lib/widgets/witnet/transactions/value_transfer/modals/general_error_tx_modal.dart
- lib/widgets/witnet/transactions/value_transfer/modals/sending_tx_modal.dart
- lib/widgets/witnet/transactions/value_transfer/modals/signing_tx_modal.dart
- lib/widgets/witnet/transactions/value_transfer/modals/successfull_transaction_modal.dart
- lib/widgets/witnet/transactions/value_transfer/modals/tx_too_large_error_modal.dart
> fix: show error modal when vtt weight exceed max vtt weight

- lib/app_lifecycle_overlay.dart
- lib/widgets/layouts/layout.dart
Checks app lifecycle and blurs the background when app is inactive:
close #293
> feat: blur background when app is inactive

- integration_test/e2e_import_xprv_from_sheikah_test.dart
- integration_test/e2e_import_xprv_test.dart
- integration_test/main.dart
- integration_test/test_utils.dart
> Test import wallet from xprv flow

- lib/screens/create_wallet/create_wallet_screen.dart
- lib/screens/preferences/general_config.dart
- lib/screens/preferences/preferences_screen.dart
- lib/screens/preferences/wallet_config.dart
- lib/widgets/layouts/layout.dart
- Avoids rebuilding the widget when overlay for inactive state is shown
> Fix overlay

- lib/util/sort_wallets_by_name.dart
- lib/widgets/layouts/dashboard_layout.dart
- lib/widgets/wallet_list.dart
- test/util/sort_wallets_by_name_test.dart
> feat: sort wallet list by name

- lib/app_lifecycle_overlay.dart
- lib/globals.dart
- lib/screens/login/bloc/login_bloc.dart
- lib/screens/login/view/biometrics_autentication.dart
> fix(innactive-app-overlay): avoid overlay when biometrics in progress

- lib/bloc/explorer/explorer_bloc.dart
- lib/bloc/transactions/value_transfer/vtt_create/vtt_create_bloc.dart
- lib/bloc/transactions/value_transfer/vtt_create/vtt_create_event.dart
- lib/bloc/transactions/value_transfer/vtt_create/vtt_create_state.dart
- lib/screens/create_wallet/build_wallet_card.dart
- lib/screens/create_wallet/disclaimer_card.dart
- lib/screens/create_wallet/enc_xprv_card.dart
- lib/screens/create_wallet/re_establish_wallet_disclaimer.dart
- lib/screens/dashboard/view/dashboard_screen.dart
- lib/screens/login/view/login_form.dart
- lib/screens/preferences/general_config.dart
- lib/screens/send_transaction/send_vtt_screen.dart
- lib/widgets/layouts/dashboard_layout.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/01_recipient_step.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/03_review_step.dart
- Avoid calls to priority estimations when results are loading
- Remove focus listeners on widget dispose
> Avoid showing inaccurate errors when sending vtt

- integration_test/e2e_auth_preferences_test.dart
- integration_test/main.dart
- integration_test/test_utils.dart
- lib/app_lifecycle_overlay.dart
- lib/bloc/transactions/value_transfer/vtt_create/vtt_create_bloc.dart
- lib/bloc/transactions/value_transfer/vtt_create/vtt_create_event.dart
- lib/bloc/transactions/value_transfer/vtt_create/vtt_create_state.dart
- lib/screens/login/bloc/login_bloc.dart
- lib/screens/login/view/login_form.dart
- lib/screens/login/view/password_validate.dart
- lib/screens/preferences/general_config.dart
- lib/screens/send_transaction/send_vtt_screen.dart
- lib/shared/api_database.dart
- lib/theme/extended_theme.dart
- lib/theme/light_theme.dart
- lib/util/allow_biometrics.dart
- lib/util/preferences.dart
- lib/widgets/PaddedButton.dart
- lib/widgets/alert_dialog.dart
- lib/widgets/input_login.dart
- lib/widgets/switch.dart
- lib/widgets/verify_password.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/01_recipient_step.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/03_review_step.dart
- lib/widgets/witnet/transactions/value_transfer/modals/unlock_keychain_modal.dart
- When biometrics are activated, the user now should type the password for validation before sending a vtt.
- Avoid loop when initial biometrics auth.
close #374
> Validate password before sending a vtt

- lib/bloc/explorer/explorer_bloc.dart
- lib/shared/api_database.dart
- lib/util/storage/database/account.dart
- lib/util/storage/database/database_isolate.dart
- lib/util/storage/database/database_service.dart
- lib/util/storage/database/transaction_repository.dart
> fix: add mintvtt to db if not saved and new utxo list

- lib/screens/dashboard/view/transactions_view.dart
- lib/widgets/transactions_list.dart
- added a `BlocListener` in the `TransactionsView` to update transaction pagination data on sync.
> fix: rebuild Transaction List on Sync

- integration_test/e2e_import_mnemonic_test.dart
- integration_test/e2e_update_wallet_test.dart
- integration_test/main.dart
> Implement e2e test for updating current wallet

- lib/bloc/transactions/value_transfer/vtt_create/vtt_create_bloc.dart
- lib/bloc/transactions/value_transfer/vtt_create/vtt_create_event.dart
- lib/screens/send_transaction/send_vtt_screen.dart
- lib/widgets/validations/amount_input.dart
- lib/widgets/validations/fee_amount_input.dart
- lib/widgets/validations/vtt_amount_input.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/01_recipient_step.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/02_select_miner_fee.dart
> fix(validation): add vtt amount to miner fee validation

- lib/screens/dashboard/view/dashboard_screen.dart
- lib/screens/dashboard/view/stats.dart
- lib/screens/dashboard/view/transactions_view.dart
- lib/screens/preferences/export_signed_msg.dart
- lib/screens/preferences/export_xprv.dart
- lib/screens/preferences/general_config.dart
- lib/screens/preferences/sign_message.dart
- lib/screens/preferences/sign_message_form.dart
- lib/screens/preferences/wallet_config.dart
- lib/screens/send_transaction/send_vtt_screen.dart
- lib/theme/dark_theme.dart
- lib/theme/light_theme.dart
- lib/widgets/address_list.dart
- lib/widgets/dashed_rect.dart
- lib/widgets/transaction_details.dart
- lib/widgets/transactions_list.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/02_select_miner_fee.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/03_review_step.dart
- Make sure the margins in all views are the same
- Add style in light and dark theme for `titleLarge`
- Adjust hide/show XPRV button size.
- Avoid border bottom in last item of `transactions_list` and `address_list`
close #413
> fix(style): update margins and titles

- .github/workflows/pull_requests.yml
- lib/util/get_localization.dart
- test/validations/vtt_amount_input_test.dart
- Run unit tests in CI
- Fix unit tests
close #424
> Fix unit tets and run them in CI

- lib/widgets/layouts/headerLayout.dart
- lib/widgets/layouts/layout.dart
- Fixes an error with the background color in the `headerLayout`
> fix(style): add correct bg color with opacity for `headerLayout`

- lib/auto_updater_overlay.dart
- lib/bloc/transactions/value_transfer/vtt_create/vtt_create_bloc.dart
- lib/constants.dart
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/widgets/layouts/layout.dart
- pubspec.yaml
- New dep: [updat.dart](https://pub.dev/packages/updat)
- Show download latest release button when new release is published
- Allow downloading latest version and open downloaded file.
close #398
> feat(update-modal): implement modal to download latest version

- android/app/src/debug/AndroidManifest.xml
- android/app/src/main/AndroidManifest.xml
- android/app/src/profile/AndroidManifest.xml
- lib/screens/login/view/init_screen.dart
- lib/shared/api_database.dart
- lib/shared/locator.dart
- lib/util/storage/database/database_isolate.dart
- lib/util/storage/database/database_service.dart
- lib/util/storage/log.dart
- lib/util/storage/log_output.dart
- lib/util/storage/path_provider_interface.dart
- pubspec.yaml
This will make sure we can debug issue #340
> Allow saving log text file for ios and android devices

- lib/shared/locator.dart
- lib/util/storage/database/database_isolate.dart
> Await initial db config

- lib/widgets/transaction_item.dart
> feat(style): add clock icon to pending status in tx

- lib/widgets/speedup_btn.dart
- lib/widgets/transaction_details.dart
- lib/widgets/transaction_item.dart
- lib/widgets/transactions_list.dart
- macos/Podfile.lock
The speed up button is now within the transaction details view.
close #447
> fix(ux): move speed up button within the transaction details view

- lib/main.dart
- lib/screens/login/view/init_screen.dart
- lib/util/storage/log_output.dart
Logs were not being written if sink initialization in `log_output` was not complete. Ensure sink is initialized when writing logs.
> fix: await set sink in `log_output`

- lib/bloc/transactions/value_transfer/vtt_create/vtt_create_bloc.dart
- lib/bloc/transactions/value_transfer/vtt_create/vtt_create_state.dart
- lib/constants.dart
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/screens/send_transaction/send_vtt_screen.dart
- lib/util/showTxConnectionError.dart
- lib/widgets/layouts/layout.dart
- lib/widgets/transactions_list.dart
- lib/widgets/witnet/transactions/value_transfer/modals/general_error_modal.dart
Block by https://github.com/witnet/witnet.dart/pull/37
close #464
> fix: show unsufficient funds error when selecting inputs

- lib/bloc/transactions/value_transfer/vtt_create/vtt_create_bloc.dart
-  Delete unused methods
- Change the visibility of private methods
> Refactor vtt create bloc

- ios/Podfile.lock
- lib/main.dart
- lib/screens/preferences/export_signed_msg.dart
- lib/util/storage/log_output.dart
- lib/util/storage/path_provider_interface.dart
- macos/Podfile.lock
The Export json option containing the message signature apparently was not working in android. If the device did not have the permission for managing external storage the user could not be redirected to the correct directory.
Requesting permission for managing external storage and adding the correct permission in the android manifest fixed it.
> fix: request permision to open directory in android

- lib/bloc/crypto/crypto_bloc.dart
> Avoid multiple simultaneous synchronizations

- devtools_options.yaml
- ios/fastlane/Fastfile
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/widgets/PaddedButton.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/01_recipient_step.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/timelock_input.dart
> Feat style advance

- android/app/build.gradle
- android/build.gradle
- android/settings.gradle
App must target Android 14 (API level 34) or higher by Aug 30
> fix: target Android 14 (API 34)

- android/app/build.gradle
- android/build.gradle
- android/settings.gradle
- integration_test/main.dart
- lib/l10n/app_en.arb
- lib/l10n/app_es.arb
- lib/util/storage/database/balance_info.dart
- lib/util/storage/database/wallet.dart
- lib/widgets/balance_details.dart
- lib/widgets/layouts/dashboard_layout.dart
- lib/widgets/stake_unstake.dart
- lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/01_recipient_step.dart
- lib/widgets/witnet/transactions/value_transfer/modals/empty_stake_modal.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile.lock
- macos/Runner/AppDelegate.swift
- pubspec.yaml
> Show stake balance

- .github/workflows/main.yml
- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
upgrade java version 11 -> 17
move namespace declaration to build.gradle
> chore: upgrade android deps

- integration_test/test_utils.dart
- lib/bloc/transactions/value_transfer/vtt_create/vtt_create_bloc.dart
- lib/util/storage/log.dart
- pubspec.yaml
when rebuilding a vtt, the change was not being properly reset
> fix: node change in VTTs

- lib/widgets/transaction_item.dart
- lib/widgets/transactions_list.dart
> fix: remove duplicate time labels

- lib/auto_updater_overlay.dart
- lib/bloc/explorer/explorer_bloc.dart
- lib/constants.dart
- lib/screens/dashboard/view/stats.dart
- lib/util/clear_and_redirect.dart
- lib/widgets/layouts/layout.dart
> Fix connection error

- .github/dependabot.yml
Add dependabot configuration file to enable automatic dependency updates
> ci: add dependabot configuration file
